site_name: mydocs-MkDocs

nav:
    - Home: index.md
    - MkDocs: mkdocs.md
    - Markdown: markdown.md
    - Imgs: imgs.md
    - Links: links.md
    - SSH: ssh.md
    - Git/Github: git.md
    - Vi/Vim: vim.md
    - Linux/Shell: linux-shell.md
    - Nginx: nginx.md
    - Databases:
        - MySQL: mysql.md
        - Mongo: mongo.md
    - Python: python.md
    - Django: django.md
    - Flask: flask.md

plugins:
    - 

# uncomment under line to use the "readthedocs" theme
theme: readthedocs


