site_name: mydocs-MkDocs

nav:
    - Home: index.md
    - MkDocs: 
      - mkdocs/mkdocs.md
      - mkdocs/markdown.md
      - mkdocs/jupyter-book.md
    - Imgs: imgs.md
    - Links: links.md
    - Fields:  
      - Geo: fields/geo.md
      - Phisics: fields/phisics.md
      - Auto-Control: fields/control.md
      - Medical: fields/medical.md
      - Algorithms and Data Structure: fields/algorithms.md
      - VR/AR/AI/DL/ML: fields/v.md
      - Behavior/Learning/Teaching: fields/blt.md
    - Sci tools:
      - Jupyter: sci-tools/jupyter.md
      - M: sci-tools/M.md
      - R: sci-tools/R.md
      - Latex: sci-tools/latex.md
    - Program Languages:
      - P: python/python.md
      - C: program-languages/C.md
      - F: program-languages/F.md
      - J: program-languages/Java.md
    - Yaml Travis-CI: 
      - mydocs yaml: yaml-travis/mydocs-yaml.md
      - yaml intro: yaml-travis/yaml.md
      - Intro: yaml-travis/travis.md 
      - Use: yaml-travis/travis-1.md
    - Git Github: git.md
    - SSH: server/ssh.md
    - Vim: server/vim.md
    - Linux Shell: 
      - Apt-pip-yum: server/apt.md
      - Linux commands: server/linux-cmds.md
      - Examples: server/examples.md
      - Linux shell: server/linux-shell.md
      - DevOps: server/bt.md
      - KVM: server/kvm.md
    - Nginx: server/nginx.md
    - Databases:
      - Sqlite: dbs/sqlite3.md
      - MySQL: dbs/mysql.md
      - Mongo: dbs/mongo.md
    - Python:  
      - Basic: python/python.md
      - Scrapy: python/scrapy.md
      - Frame:
        - Django: python/django.md
        - Flask: python/flask.md
    - Back end:
      - XML: back-end/xml.md
      - SOAP: back-end/soap.md
      - Django: python/django.md
      - Flask: python/flask.md
      - Tornado: python/tornado.md
    - Front end:
      - front-end/html.md
      - front-end/css.md
      - front-end/json.md
      - front-end/js.md
      - front-end/jquery.md
      - front-end/ajax.md
      - Frame:
        - front-end/bootstrap.md
        - front-end/layui.md
        - front-end/xadmin.md
    - NAT: 
      - nat/frp.md
      - nat/openwrt.md
      - nat/zerotieone.md
    - Cheat-Sheets: cheat-sheets.md
    - Diary-2020-3: 
        - Test: diaries/0.md
        - First day: diaries/20200303.md
        - Second day: diaries/4.md

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - footnotes
  - meta
  - admonition
  - codehilite
  - toc:
      permalink: true

# add plugins
plugins:
  - search
  - minify:
      minify_html: true
  - search
  - git-revision-date-localized:
      type: iso_datetime

# uncomment under line to use the "readthedocs" theme
# theme: readthedocs
# Need to install `pip install mkdocs-material`
theme: 
  name: 'material'
# custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'green'
    accent: 'green'
  font:
    text: 'Ubuntu'
    #    code: 'Ubuntu Mono'
    code: 'Consolas'
  logo: 'imgs/ico-head.jpg'
# language: 'zh'
  language: 'en'

extra:
  search:
    language: 'en'
    tokenizer: '[\s\-\.]+'
  social:
    - type: 'github'
      link: 'https://github.com/dick7'
    - type: 'gitee'
      link: 'https://gitee.com/dick7_love'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/dick7_love'
    - type: 'juejin'
      link: 'https://juejin.im/user/5e5e5768e51d4526d43f3ac6'
    - type: 'kuaishou'
      link: 'https://live.kuaishou.com/profile/3xn5rycf9cpr9s4'
    - type: 'wechat'
      link: 'https://wx.qq.com/dick7_love'
    - tpye: 'zhihu'
      link: 'https://www.zhihu.com/people/dick7'
    - type: 'douban'
      link: 'https://www.douban.com/people/168395085/'
    - type: 'jianshu'
      link: 'https://www.jianshu.com/u/cfae97b3b879'
    - type: 'alipay'
      link: 'https://my.alipay.com/portal/i.htm'
    - type: 'taobao'
      link: 'https://i.taobao.com/'
    - type: 'qq'
      link: 'https://im.qq.com/549119612'
    - type: 'baidu'
      link: 'http://i.baidu.com/'
    - type: 'lofter'
      link: 'https://qichangyu123456789.lofter.com/'
    - type: 'sina'
      link: 'https://weibo.com/u/6054906548/home?wvr=5'
    - type: 'new-realm'
      link: 'http://blog.new-realm.cn/'
    - type: 'ztloadfield'
      link: 'http://dev.ztloadfield.com/'
  manifest: 'manifest.webmanifest'

# google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'

repo_name: 'dick7/mydocs'
repo_url: 'https://github.com/dick7/mydocs'

copyright: 'Copyright &copy; 2020 - 2021 Dick Sven'

