site_name: mydocs-MkDocs

nav:
    - Home: index.md
    - MkDocs: mkdocs.md
    - Markdown: markdown.md
    - Fields: fields.md
    - Imgs: imgs.md
    - Links: links.md
    - SSH: ssh.md
    - Git/Github: git.md
    - Vi/Vim: vim.md
    - Linux/Shell: linux-shell.md
    - Nginx: nginx.md
    - Databases:
        - MySQL: dbs/mysql.md
        - Mongo: dbs/mongo.md
    - Python: python.md
    - Django: django.md
    - Flask: flask.md
    - Cheat-Sheets: cheat-sheets.md
    - Diary-2020-3: 
        - Test: diaries/0.md
        - First day: diaries/20200303.md
        - Second day: diaries/4.md

## add plugins
# plugins:
#   - 

# uncomment under line to use the "readthedocs" theme
# theme: readthedocs


