site_name: Hello MkDocs

nav:
    - Home: index.md
    - Markdown: markdown.md
    - Imgs: imgs.md
    - Links: links.md
    - Help: Help.md

# uncomment under line to use the "readthedocs" theme
# theme: readthedocs
